/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ClawdianPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var AGENT_COLORS = [
  "#6366f1",
  // Indigo (Nexus)
  "#f97316",
  // Orange (Aristotowl)
  "#10b981",
  // Emerald
  "#ec4899",
  // Pink
  "#8b5cf6",
  // Purple
  "#06b6d4",
  // Cyan
  "#f43f5e",
  // Rose
  "#84cc16",
  // Lime
  "#f59e0b",
  // Amber
  "#14b8a6"
  // Teal
];
var DEFAULT_AGENT_COLORS = {
  "main": "#6366f1",
  "nexus": "#6366f1",
  "aristotowl": "#f97316",
  "prism": "#ec4899",
  "orion": "#10b981"
};
var DEFAULT_SETTINGS = {
  gatewayUrl: "wss://your-machine.tailXXXX.ts.net",
  defaultAgent: "",
  lastAgent: "",
  agentColors: {},
  includeVaultContext: true,
  includeChatHistory: true,
  chatHistoryDepth: 5,
  contextSize: "large",
  autoConnect: false
};
var CONTEXT_SIZES = {
  "small": { label: "Small (500 chars)", chars: 500 },
  "medium": { label: "Medium (1500 chars)", chars: 1500 },
  "large": { label: "Large (3000 chars)", chars: 3e3 },
  "max": { label: "Max (entire file)", chars: Infinity }
};
var ClawdianSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.selectedColorAgentId = "";
    this.colorPickerEl = null;
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const isConnected = this.plugin.client.isConnected();
    const agents = this.plugin.client.getAgents();
    if (!this.selectedColorAgentId && agents.length > 0) {
      this.selectedColorAgentId = agents[0].id;
    }
    new import_obsidian.Setting(containerEl).setName("Connection").setHeading();
    new import_obsidian.Setting(containerEl).setName("Status").setDesc(isConnected ? "\u2705 Connected" : "\u274C Disconnected").addButton((btn) => {
      if (isConnected) {
        btn.setButtonText("Disconnect").onClick(() => {
          this.plugin.client.disconnect();
          new import_obsidian.Notice("Disconnected");
          this.display();
        });
      } else {
        btn.setButtonText("Connect").setCta().onClick(() => {
          void this.plugin.tryConnect().then(() => {
            this.display();
          });
        });
      }
    });
    new import_obsidian.Setting(containerEl).setName("Gateway URL").setDesc("OpenClaw gateway WebSocket URL").addText((text) => text.setPlaceholder("wss://your-gateway-url").setValue(this.plugin.settings.gatewayUrl).onChange((value) => {
      this.plugin.settings.gatewayUrl = value;
      void this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Auto-connect on startup").setDesc("Automatically connect when Obsidian starts").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoConnect).onChange((value) => {
      this.plugin.settings.autoConnect = value;
      void this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Reset token").setDesc("Clear stored gateway token (you'll need to re-enter it)").addButton((btn) => {
      btn.setButtonText("Clear token").setWarning().onClick(() => {
        void this.plugin.clearToken();
        new import_obsidian.Notice("Token cleared. Reconnect to enter a new token.");
      });
    });
    new import_obsidian.Setting(containerEl).setName("Preferences").setHeading();
    const agentSetting = new import_obsidian.Setting(containerEl).setName("Default agent").setDesc("Which agent to chat with by default");
    agentSetting.addDropdown((dropdown) => {
      if (agents.length > 0) {
        agents.forEach((agent) => {
          dropdown.addOption(agent.id, agent.name || agent.id);
        });
      } else {
        dropdown.addOption("", "Connect to see agents");
      }
      dropdown.setValue(this.plugin.settings.lastAgent || this.plugin.settings.defaultAgent);
      dropdown.onChange((value) => {
        this.plugin.settings.defaultAgent = value;
        this.plugin.settings.lastAgent = value;
        void this.plugin.saveSettings();
        this.display();
      });
    });
    if (agents.length > 0) {
      const colorSetting = new import_obsidian.Setting(containerEl).setName("Agent color").setDesc("Customize chat color for selected agent");
      colorSetting.addDropdown((dropdown) => {
        agents.forEach((agent) => {
          dropdown.addOption(agent.id, agent.name || agent.id);
        });
        dropdown.setValue(this.selectedColorAgentId);
        dropdown.onChange((value) => {
          this.selectedColorAgentId = value;
          const color = this.plugin.settings.agentColors[value] || DEFAULT_AGENT_COLORS[value] || AGENT_COLORS[0];
          if (this.colorPickerEl) {
            this.colorPickerEl.setValue(color);
          }
        });
      });
      colorSetting.addColorPicker((picker) => {
        const color = this.plugin.settings.agentColors[this.selectedColorAgentId] || DEFAULT_AGENT_COLORS[this.selectedColorAgentId] || AGENT_COLORS[0];
        picker.setValue(color);
        this.colorPickerEl = picker;
        picker.onChange((value) => {
          this.plugin.settings.agentColors[this.selectedColorAgentId] = value;
          void this.plugin.saveSettings();
        });
      });
    }
    new import_obsidian.Setting(containerEl).setName("Context").setHeading();
    new import_obsidian.Setting(containerEl).setName("Include vault context").setDesc("Send current file as context with messages").addToggle((toggle) => toggle.setValue(this.plugin.settings.includeVaultContext).onChange((value) => {
      this.plugin.settings.includeVaultContext = value;
      void this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Context size").setDesc("Maximum characters from file to include").addDropdown((dropdown) => {
      dropdown.addOption("small", "Small (500 chars)");
      dropdown.addOption("medium", "Medium (1500 chars)");
      dropdown.addOption("large", "Large (3000 chars)");
      dropdown.addOption("max", "Max (entire file)");
      dropdown.setValue(this.plugin.settings.contextSize);
      dropdown.onChange((value) => {
        this.plugin.settings.contextSize = value;
        void this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Include chat history").setDesc("Include previous messages as context").addToggle((toggle) => toggle.setValue(this.plugin.settings.includeChatHistory).onChange((value) => {
      this.plugin.settings.includeChatHistory = value;
      void this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Chat history depth").setDesc("Number of previous messages to include").addDropdown((dropdown) => {
      dropdown.addOption("1", "Last 1 message");
      dropdown.addOption("3", "Last 3 messages");
      dropdown.addOption("5", "Last 5 messages");
      dropdown.addOption("10", "Last 10 messages");
      dropdown.setValue(this.plugin.settings.chatHistoryDepth.toString());
      dropdown.onChange((value) => {
        this.plugin.settings.chatHistoryDepth = parseInt(value);
        void this.plugin.saveSettings();
      });
    });
  }
};

// src/components/ChatView.ts
var import_obsidian2 = require("obsidian");
var VIEW_TYPE_CHAT = "clawdian-chat-view";
var ChatView = class extends import_obsidian2.ItemView {
  constructor(leaf, client, plugin) {
    super(leaf);
    this.connectOverlayEl = null;
    this.inputContainerEl = null;
    this.agentSelectEl = null;
    this.loadingEl = null;
    this.contextBarEl = null;
    this.attachedFiles = [];
    this.isLoading = false;
    this.isStreaming = false;
    this.currentStreamingMessage = null;
    this.streamingText = "";
    this.sessionIds = /* @__PURE__ */ new Map();
    this.responseTimeout = null;
    this.statusPollingInterval = null;
    this.currentRunId = null;
    this.currentAgentId = "";
    this.messageStartTime = 0;
    this.hasShownConnected = false;
    this.processedRunIds = /* @__PURE__ */ new Set();
    this.RESPONSE_TIMEOUT_MS = 6e4;
    this.STATUS_POLLING_MS = 6e4;
    this.commandPaletteEl = null;
    this.client = client;
    this.plugin = plugin;
    this.sessionId = "obsidian-chat-" + this.generateSessionId();
  }
  getViewType() {
    return VIEW_TYPE_CHAT;
  }
  getDisplayText() {
    return "Clawchat";
  }
  getIcon() {
    return "message-square";
  }
  async onOpen() {
    await Promise.resolve();
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("clawdian-chat-container");
    const header = container.createEl("div", { cls: "clawdian-header" });
    header.createEl("span", { text: "\u{1F99E} Clawchat", cls: "clawdian-title" });
    const headerRight = header.createEl("div", { cls: "clawdian-header-right" });
    headerRight.createEl("label", { text: "Agent:", cls: "clawdian-agent-label" });
    this.agentSelectEl = headerRight.createEl("select", { cls: "clawdian-agent-select" });
    this.messagesEl = container.createEl("div", { cls: "clawdian-messages" });
    setTimeout(() => {
      void this.renderHistory();
    }, 50);
    this.loadingEl = container.createEl("div", { cls: "clawdian-loading" });
    this.loadingEl.createEl("div", { cls: "clawdian-spinner" });
    this.loadingEl.createEl("span", { cls: "clawdian-loading-text" });
    this.updateLoadingText();
    this.loadingEl.addClass("clawdian-hidden");
    this.createConnectOverlay(container);
    this.contextBarEl = container.createEl("div", { cls: "clawdian-context-bar" });
    this.contextBarEl.addClass("clawdian-hidden");
    this.registerEvent(this.app.workspace.on("active-leaf-change", () => {
      this.updateCurrentFile();
    }));
    this.initContextFiles();
    this.inputContainerEl = container.createEl("div", { cls: "clawdian-input-container" });
    this.inputContainerEl.addClass("clawdian-hidden");
    this.inputEl = this.inputContainerEl.createEl("textarea", {
      cls: "clawdian-input",
      attr: { placeholder: "Type your message..." }
    });
    const sendBtn = this.inputContainerEl.createEl("button", {
      cls: "clawdian-send-btn",
      text: "Send"
    });
    sendBtn.addEventListener("click", () => {
      void this.sendMessage();
    });
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.sendMessage();
      }
    });
    this.inputEl.addEventListener("input", () => this.handleSlashCommands());
    this.setupCallbacks();
    if (this.client.isConnected()) {
      this.showConnected();
    } else {
      this.showConnectOverlay();
    }
  }
  createConnectOverlay(container) {
    this.connectOverlayEl = container.createEl("div", { cls: "clawdian-connect-overlay" });
    this.connectOverlayEl.addClass("clawdian-hidden");
    const overlayContent = this.connectOverlayEl.createEl("div", { cls: "clawdian-connect-overlay-content" });
    overlayContent.createEl("h2", { text: "Connect to OpenClaw" });
    const instructions = overlayContent.createEl("div", { cls: "clawdian-instructions" });
    instructions.createEl("p", { text: "To connect:" });
    const ol = instructions.createEl("ol");
    const step1 = ol.createEl("li");
    step1.createEl("span", { text: "Run " });
    step1.createEl("code", { text: "openclaw dashboard" });
    ol.createEl("li", { text: 'Click "Overview" and copy the gateway token' });
    ol.createEl("li", { text: "Click Connect below and paste the token" });
    const connectBtn = overlayContent.createEl("button", {
      cls: "clawdian-connect-btn",
      text: "Connect"
    });
    connectBtn.addEventListener("click", () => {
      void (async () => {
        const connected = await this.plugin.tryConnect();
        if (!connected) {
          this.plugin.showTokenModal();
        }
      })();
    });
    void connectBtn;
  }
  showConnectOverlay() {
    if (this.connectOverlayEl) {
      this.connectOverlayEl.removeClass("clawdian-hidden");
      this.connectOverlayEl.addClass("clawdian-visible");
    }
  }
  hideConnectOverlay() {
    if (this.connectOverlayEl) {
      this.connectOverlayEl.addClass("clawdian-hidden");
    }
  }
  setupCallbacks() {
    this.client.onMessage = async (text) => {
      var _a, _b, _c, _d, _e;
      try {
        const data = JSON.parse(text);
        if (data.type === "event" && data.event === "agent") {
          const payload = data.payload;
          if (payload == null ? void 0 : payload.sessionKey) {
            const messageSessionId = payload.sessionKey.split(":session:")[1];
            if (messageSessionId !== this.sessionId) return;
          }
          if ((payload == null ? void 0 : payload.stream) === "lifecycle") {
            if (((_a = payload == null ? void 0 : payload.data) == null ? void 0 : _a.phase) === "start") {
              this.messageStartTime = Date.now();
            }
          }
          if ((payload == null ? void 0 : payload.state) === "error") {
            const errorMsg = (payload == null ? void 0 : payload.error) || "An error occurred";
            const isAborted = errorMsg.includes("aborted") || errorMsg.includes("timeout");
            this.hideLoading();
            if (isAborted) {
              this.showErrorText("\u26A0\uFE0F Agent timed out after 10 minutes. Try a shorter request.");
            } else {
              this.showErrorText("\u26A0\uFE0F " + errorMsg);
            }
          }
          return;
        }
        if (data.type === "event" && data.event === "chat") {
          const payload = data.payload;
          if (payload == null ? void 0 : payload.sessionKey) {
            const messageSessionId = payload.sessionKey.split(":session:")[1];
            if (messageSessionId !== this.sessionId) return;
          }
          if ((payload == null ? void 0 : payload.state) === "final" && ((_b = payload == null ? void 0 : payload.message) == null ? void 0 : _b.content)) {
            const runId = payload.runId;
            if (runId && this.processedRunIds.has(runId)) {
              return;
            }
            if (runId) {
              this.processedRunIds.add(runId);
              if (this.processedRunIds.size > 100) {
                const ids = Array.from(this.processedRunIds);
                this.processedRunIds = new Set(ids.slice(-50));
              }
            }
            const textContent = payload.message.content.filter((item) => item.type === "text").map((item) => item.text || "").join("");
            const agentId = payload.agent || ((_c = this.agentSelectEl) == null ? void 0 : _c.value) || this.plugin.settings.defaultAgent || "main";
            const agentName = ((_e = (_d = this.agentSelectEl) == null ? void 0 : _d.options[this.agentSelectEl.selectedIndex]) == null ? void 0 : _e.text) || agentId;
            const agentEmoji = this.getAgentEmoji(agentId);
            await this.plugin.addMessageToHistory({
              agentId,
              agentName,
              agentEmoji,
              role: "assistant",
              content: textContent
            });
            this.hideLoading();
            this.addMessage("assistant", textContent, agentEmoji);
          }
          return;
        }
      } catch (e) {
      }
    };
    this.client.onConnect = () => {
      this.showConnected();
      void this.fetchAndUpdateAgents();
    };
    this.client.onAgentsUpdated = (agents) => {
      this.populateAgentDropdown(agents);
    };
    this.client.onDisconnect = () => {
      this.showDisconnected();
    };
    this.client.onAuthError = (msg) => {
      this.showDisconnected();
      this.plugin.showTokenModal();
    };
  }
  sanitizeInput(input) {
    return input.replace(/[<>]/g, "").trim();
  }
  validateCommand(cmdId) {
    const allowedCommands = ["search", "create", "summarize", "clear"];
    return allowedCommands.includes(cmdId);
  }
  async handleConnect() {
    if (this.client.isConnected()) {
      this.client.disconnect();
      this.showDisconnected();
      return;
    }
    const connected = await this.plugin.tryConnect();
    if (connected) {
      this.showConnected();
    } else {
      this.plugin.showTokenModal();
    }
  }
  async fetchAndUpdateAgents() {
    const agents = await this.client.fetchAgents();
    this.populateAgentDropdown(agents);
  }
  getAgentColor(agentId) {
    return this.plugin.settings.agentColors[agentId] || DEFAULT_AGENT_COLORS[agentId] || AGENT_COLORS[0];
  }
  getAgentEmoji(agentId) {
    var _a;
    const agents = this.client.getAgents();
    const agent = agents.find((a) => a.id === agentId);
    return (_a = agent == null ? void 0 : agent.identity) == null ? void 0 : _a.emoji;
  }
  getAgentDisplayInfo(agentId) {
    var _a, _b, _c;
    const agents = this.client.getAgents();
    const agent = agents.find((a) => a.id === agentId);
    const agentName = (agent == null ? void 0 : agent.name) || agentId;
    const agentColor = this.getAgentColor(agentId);
    let avatar = agentName.charAt(0).toUpperCase();
    let useImageAvatar = false;
    if ((_a = agent == null ? void 0 : agent.identity) == null ? void 0 : _a.emoji) avatar = agent.identity.emoji;
    else if ((_b = agent == null ? void 0 : agent.identity) == null ? void 0 : _b.avatarUrl) {
      avatar = agent.identity.avatarUrl;
      useImageAvatar = true;
    } else if ((_c = agent == null ? void 0 : agent.identity) == null ? void 0 : _c.avatar) {
      avatar = agent.identity.avatar;
      useImageAvatar = true;
    }
    return { avatar, useImageAvatar, color: agentColor, name: agentName };
  }
  populateAgentDropdown(agents) {
    if (!this.agentSelectEl) return;
    this.agentSelectEl.empty();
    const agentsList = (agents == null ? void 0 : agents.length) ? agents : this.client.getAgents();
    if (agentsList.length === 0) {
      this.agentSelectEl.createEl("option", {
        text: "No agents available",
        value: "",
        attr: { disabled: "true", selected: "true" }
      });
    } else {
      agentsList.forEach((agent) => {
        const option = this.agentSelectEl.createEl("option", {
          text: agent.name || agent.id,
          value: agent.id
        });
        const selectedAgent = this.plugin.settings.lastAgent || this.plugin.settings.defaultAgent;
        if (agent.id === selectedAgent) option.selected = true;
      });
      this.agentSelectEl.addEventListener("change", () => {
        void (async () => {
          var _a;
          const selectedValue = (_a = this.agentSelectEl) == null ? void 0 : _a.value;
          if (selectedValue) {
            this.plugin.settings.lastAgent = selectedValue;
            await this.plugin.saveSettings();
            if (!this.sessionIds.has(selectedValue)) {
              this.sessionIds.set(selectedValue, "obsidian-chat-" + this.generateSessionId());
            }
            this.sessionId = this.sessionIds.get(selectedValue);
            this.currentAgentId = selectedValue;
            this.renderHistory();
          }
        })();
      });
    }
  }
  showConnected() {
    this.hideConnectOverlay();
    if (this.connectOverlayEl) this.connectOverlayEl.addClass("clawdian-hidden");
    if (this.contextBarEl) {
      this.contextBarEl.removeClass("clawdian-hidden");
      this.contextBarEl.addClass("clawdian-visible");
    }
    if (this.inputContainerEl) {
      this.inputContainerEl.removeClass("clawdian-hidden");
      this.inputContainerEl.addClass("clawdian-visible");
    }
    if (!this.hasShownConnected) {
      new import_obsidian2.Notice("\u{1F99E} Connected");
      this.hasShownConnected = true;
    }
  }
  showDisconnected() {
    if (!this.plugin.settings.autoConnect) {
      this.showConnectOverlay();
    }
    if (this.contextBarEl) this.contextBarEl.addClass("clawdian-hidden");
    if (this.inputContainerEl) this.inputContainerEl.addClass("clawdian-hidden");
  }
  renderHistory() {
    var _a;
    if (!this.messagesEl) return;
    this.messagesEl.empty();
    const messages = ((_a = this.plugin.chatHistory) == null ? void 0 : _a.messages) || [];
    if (!messages || messages.length === 0) {
      this.messagesEl.createEl("div", {
        cls: "clawdian-empty-history",
        text: "No chat history yet. Start a conversation!"
      });
      return;
    }
    messages.forEach((msg) => {
      this.renderMessage(msg);
    });
    requestAnimationFrame(() => {
      this.messagesEl.scrollTop = this.messagesEl.scrollHeight;
    });
  }
  renderMessage(msg) {
    var _a, _b, _c;
    const agentId = msg.agentId;
    const agentName = msg.agentName || agentId;
    const agentColor = this.getAgentColor(agentId);
    const agents = this.client.getAgents();
    const agent = agents.find((a) => a.id === agentId);
    let avatar = agentName.charAt(0).toUpperCase();
    let useImageAvatar = false;
    if (msg.agentEmoji) avatar = msg.agentEmoji;
    else if ((_a = agent == null ? void 0 : agent.identity) == null ? void 0 : _a.emoji) avatar = agent.identity.emoji;
    else if ((_b = agent == null ? void 0 : agent.identity) == null ? void 0 : _b.avatarUrl) {
      avatar = agent.identity.avatarUrl;
      useImageAvatar = true;
    } else if ((_c = agent == null ? void 0 : agent.identity) == null ? void 0 : _c.avatar) {
      avatar = agent.identity.avatar;
      useImageAvatar = true;
    }
    if (msg.role === "user") {
      const msgContainer = this.messagesEl.createEl("div", {
        cls: "clawdian-message-container clawdian-message-container-user"
      });
      const block = msgContainer.createEl("div", { cls: "clawdian-message-block clawdian-user-block" });
      block.createEl("div", { cls: "clawdian-message-sender clawdian-user-sender", text: "You" });
      block.createEl("div", { cls: "clawdian-message-bubble clawdian-user-bubble", text: msg.content });
    } else {
      const msgContainer = this.messagesEl.createEl("div", {
        cls: "clawdian-message-container clawdian-message-container-agent"
      });
      msgContainer.style.setProperty("--agent-color", agentColor);
      const avatarEl = msgContainer.createEl("div", { cls: "clawdian-avatar" });
      if (useImageAvatar) {
        const img = avatarEl.createEl("img", { cls: "clawdian-avatar-img", attr: { src: avatar, alt: agentName } });
        img.onerror = () => {
          avatarEl.empty();
          avatarEl.setText(agentName.charAt(0).toUpperCase());
        };
      } else {
        avatarEl.setText(avatar);
      }
      avatarEl.style.setProperty("--clawdian-avatar-color", agentColor);
      const block = msgContainer.createEl("div", { cls: "clawdian-message-block" });
      block.createEl("div", { cls: "clawdian-message-sender", text: agentName });
      block.createEl("div", { cls: "clawdian-message-bubble", text: msg.content });
    }
  }
  initContextFiles() {
    if (this.plugin.settings.includeVaultContext && this.attachedFiles.length === 0) {
      const activeFile = this.app.workspace.getActiveFile();
      if (activeFile && activeFile.extension === "md") {
        this.attachedFiles.push({ path: activeFile.path, name: activeFile.name });
      }
    }
    this.renderContextBar();
  }
  updateCurrentFile() {
    if (this.attachedFiles.length === 0 && this.plugin.settings.includeVaultContext) {
      const activeFile = this.app.workspace.getActiveFile();
      if (activeFile && activeFile.extension === "md") {
        this.attachedFiles.push({ path: activeFile.path, name: activeFile.name });
        this.renderContextBar();
      }
    }
  }
  renderContextBar() {
    if (!this.contextBarEl) return;
    this.contextBarEl.empty();
    const addBtn = this.contextBarEl.createEl("button", {
      cls: "clawdian-context-add-btn",
      text: "+ Add file"
    });
    addBtn.addEventListener("click", () => {
      new FileSuggestModal(this.app, this).open();
    });
    this.attachedFiles.forEach((file, index) => {
      if (!this.contextBarEl) return;
      const chip = this.contextBarEl.createEl("div", { cls: "clawdian-context-file-chip" });
      chip.createEl("span", { text: file.name, cls: "clawdian-context-file-name" });
      const removeBtn = chip.createEl("button", { cls: "clawdian-context-file-remove", text: "\xD7" });
      removeBtn.addEventListener("click", () => {
        this.attachedFiles.splice(index, 1);
        this.renderContextBar();
      });
    });
  }
  addFile(file) {
    if (!file || !file.path) {
      new import_obsidian2.Notice("Invalid file");
      return;
    }
    if (this.attachedFiles.some((f) => f.path === file.path)) {
      new import_obsidian2.Notice("File already attached");
      return;
    }
    this.attachedFiles.push({ path: file.path, name: file.name });
    this.renderContextBar();
  }
  async sendMessage() {
    var _a, _b, _c, _d;
    if (!this.client.isConnected()) {
      new import_obsidian2.Notice("Not connected. Click Connect first.");
      return;
    }
    if (this.isLoading) return;
    const text = this.inputEl.value.trim();
    const MAX_MESSAGE_LENGTH = 5e4;
    if (text.length > MAX_MESSAGE_LENGTH) {
      new import_obsidian2.Notice("Message too long. Maximum " + MAX_MESSAGE_LENGTH + " characters.");
      return;
    }
    if (!text) return;
    if (text.startsWith("/")) {
      const match = text.match(/^\/(\w+)(?:\s+(.*))?$/);
      if (match) {
        const commandId = match[1];
        const args = match[2] || "";
        if (this.validateCommand(commandId)) {
          this.inputEl.value = "";
          await this.executeCommand(commandId, args);
          return;
        }
      }
    }
    const agentId = ((_a = this.agentSelectEl) == null ? void 0 : _a.value) || this.plugin.settings.defaultAgent || "main";
    const agentName = ((_c = (_b = this.agentSelectEl) == null ? void 0 : _b.options[this.agentSelectEl.selectedIndex]) == null ? void 0 : _c.text) || agentId;
    const agentEmoji = this.getAgentEmoji(agentId);
    await this.plugin.addMessageToHistory({
      agentId,
      agentName,
      agentEmoji,
      role: "user",
      content: text
    });
    this.addMessage("user", text);
    this.inputEl.value = "";
    this.showLoading();
    const context = {};
    const maxChars = CONTEXT_SIZES[this.plugin.settings.contextSize].chars;
    if (this.attachedFiles.length > 0) {
      const fileContents = [];
      for (const file of this.attachedFiles) {
        try {
          const tfile = this.app.vault.getAbstractFileByPath(file.path);
          if (tfile instanceof import_obsidian2.TFile) {
            const content = await this.app.vault.read(tfile);
            const truncated = maxChars === Infinity ? content : content.slice(0, maxChars);
            fileContents.push(`--- ${file.name} ---
${truncated}`);
          }
        } catch (e) {
          void e;
        }
      }
      if (fileContents.length > 0) {
        context.currentFile = this.attachedFiles.map((f) => f.path).join(", ");
        context.fileContent = fileContents.join("\n\n");
      }
    }
    try {
      const selectedAgent = ((_d = this.agentSelectEl) == null ? void 0 : _d.value) || this.plugin.settings.defaultAgent;
      const runId = await this.client.sendMessage({
        agent: selectedAgent,
        content: text,
        context,
        sessionId: this.sessionId
      });
      this.currentRunId = runId;
    } catch (err) {
      this.hideLoading();
      this.addMessage("assistant", "\u26A0\uFE0F Failed to send. Connection lost?");
      void err;
    }
  }
  addMessage(role, text, savedEmoji) {
    var _a, _b, _c, _d, _e, _f;
    const agentId = ((_a = this.agentSelectEl) == null ? void 0 : _a.value) || this.plugin.settings.defaultAgent || "main";
    const agentName = role === "user" ? "You" : ((_c = (_b = this.agentSelectEl) == null ? void 0 : _b.options[this.agentSelectEl.selectedIndex]) == null ? void 0 : _c.text) || agentId;
    const agentColor = role === "user" ? "" : this.getAgentColor(agentId);
    const agents = this.client.getAgents();
    const agent = agents.find((a) => a.id === agentId);
    let avatar = agentName.charAt(0).toUpperCase();
    let useImageAvatar = false;
    if (savedEmoji) avatar = savedEmoji;
    else if ((_d = agent == null ? void 0 : agent.identity) == null ? void 0 : _d.emoji) avatar = agent.identity.emoji;
    else if ((_e = agent == null ? void 0 : agent.identity) == null ? void 0 : _e.avatarUrl) {
      avatar = agent.identity.avatarUrl;
      useImageAvatar = true;
    } else if ((_f = agent == null ? void 0 : agent.identity) == null ? void 0 : _f.avatar) {
      avatar = agent.identity.avatar;
      useImageAvatar = true;
    }
    if (role === "user") {
      const msgContainer = this.messagesEl.createEl("div", {
        cls: "clawdian-message-container clawdian-message-container-user"
      });
      const block = msgContainer.createEl("div", { cls: "clawdian-message-block clawdian-user-block" });
      block.createEl("div", { cls: "clawdian-message-sender clawdian-user-sender", text: "You" });
      block.createEl("div", { cls: "clawdian-message-bubble clawdian-user-bubble", text });
    } else {
      const msgContainer = this.messagesEl.createEl("div", {
        cls: "clawdian-message-container clawdian-message-container-agent"
      });
      msgContainer.style.setProperty("--agent-color", agentColor);
      const avatarEl = msgContainer.createEl("div", { cls: "clawdian-avatar" });
      if (useImageAvatar) {
        const img = avatarEl.createEl("img", { cls: "clawdian-avatar-img", attr: { src: avatar, alt: agentName } });
        img.onerror = () => {
          avatarEl.empty();
          avatarEl.setText(agentName.charAt(0).toUpperCase());
        };
        void img;
      } else {
        avatarEl.setText(avatar);
      }
      avatarEl.style.setProperty("--clawdian-avatar-color", agentColor);
      const block = msgContainer.createEl("div", { cls: "clawdian-message-block" });
      block.createEl("div", { cls: "clawdian-message-sender", text: agentName });
      block.createEl("div", { cls: "clawdian-message-bubble", text });
    }
    requestAnimationFrame(() => {
      this.messagesEl.scrollTop = this.messagesEl.scrollHeight;
    });
  }
  showLoading() {
    this.isLoading = true;
    if (this.loadingEl) {
      this.loadingEl.removeClass("clawdian-hidden");
      this.loadingEl.addClass("clawdian-visible");
    }
    requestAnimationFrame(() => {
      this.messagesEl.scrollTop = this.messagesEl.scrollHeight;
    });
    this.startStatusPolling();
  }
  hideLoading() {
    this.isLoading = false;
    if (this.loadingEl) this.loadingEl.addClass("clawdian-hidden");
    this.stopStatusPolling();
    if (this.responseTimeout) {
      clearTimeout(this.responseTimeout);
      this.responseTimeout = null;
    }
  }
  updateLoadingText() {
    var _a, _b;
    if (!this.loadingEl) return;
    const agentId = ((_a = this.agentSelectEl) == null ? void 0 : _a.value) || this.plugin.settings.defaultAgent || "Agent";
    const agentName = (this.agentSelectEl && this.agentSelectEl.selectedIndex >= 0 ? (_b = this.agentSelectEl.options[this.agentSelectEl.selectedIndex]) == null ? void 0 : _b.text : null) || agentId;
    const loadingText = this.loadingEl.querySelector(".clawdian-loading-text");
    if (loadingText) loadingText.setText(`${agentName} is thinking...`);
  }
  startStatusPolling() {
    this.stopStatusPolling();
    this.statusPollingInterval = setInterval(() => {
      void this.checkSessionStatus();
    }, this.STATUS_POLLING_MS);
  }
  stopStatusPolling() {
    if (this.statusPollingInterval) {
      clearInterval(this.statusPollingInterval);
      this.statusPollingInterval = null;
    }
  }
  async checkSessionStatus() {
    var _a;
    if (!this.sessionId || !this.client.isConnected()) return;
    const elapsed = Date.now() - this.messageStartTime;
    const elapsedMin = Math.floor(elapsed / 6e4);
    if (elapsedMin >= 8 && elapsedMin < 9) {
      this.showInfoText("\u26A0\uFE0F Agent taking >8 minutes - will timeout at 10 min. Consider cancelling.");
    } else if (elapsedMin >= 5 && elapsedMin < 6) {
      this.showInfoText("\u23F3 Still processing (>5 min). Gateway timeout at 10 min.");
    } else if (elapsedMin >= 3 && elapsedMin < 4) {
      this.showInfoText("\u23F3 This is taking longer than usual (>3 min)...");
    } else if (elapsedMin >= 1 && elapsedMin < 2) {
      this.showInfoText("\u23F3 Agent is thinking...");
    }
    const selectedAgent = ((_a = this.agentSelectEl) == null ? void 0 : _a.value) || this.plugin.settings.defaultAgent || "main";
    const sessionKey = `agent:${selectedAgent}:session:${this.sessionId}`;
    try {
      const status = await this.client.getSessionStatus(sessionKey);
      if (status === "error" || status === "aborted" || status === "timeout") {
        this.hideLoading();
        this.showErrorText("\u26A0\uFE0F Agent timed out or failed. Please try again.");
      }
    } catch (err) {
      void err;
    }
  }
  showInfoText(text) {
    const infoEl = this.messagesEl.createEl("div", { cls: "clawdian-info-text", text });
    setTimeout(() => {
      infoEl.remove();
    }, 5e3);
    this.messagesEl.scrollTop = this.messagesEl.scrollHeight;
  }
  showErrorText(text) {
    const errorEl = this.messagesEl.createEl("div", { cls: "clawdian-error-text", text });
    void errorEl;
    this.messagesEl.scrollTop = this.messagesEl.scrollHeight;
  }
  generateSessionId() {
    return Date.now().toString(36) + Math.random().toString(36).substring(2, 9);
  }
  handleSlashCommands() {
    const text = this.inputEl.value;
    if (text.startsWith("/")) {
      this.showCommandPalette();
    }
  }
  showCommandPalette() {
    if (this.commandPaletteEl) {
      this.commandPaletteEl.remove();
      this.commandPaletteEl = null;
    }
    const commands = [
      { id: "search", label: "/search <query> - Search vault and include results", icon: "search" },
      { id: "create", label: "/create <title> - Create a new note", icon: "file-plus" },
      { id: "summarize", label: "/summarize - Summarize current note", icon: "file-text" },
      { id: "clear", label: "/clear - Clear chat history", icon: "trash" }
    ];
    const palette = document.createElement("div");
    palette.className = "clawdian-command-palette";
    this.commandPaletteEl = palette;
    commands.forEach((cmd) => {
      const item = palette.createEl("div", { cls: "clawdian-command-item" });
      item.createEl("span", { text: cmd.label, cls: "clawdian-command-label" });
      item.addEventListener("click", () => {
        this.executeCommand(cmd.id);
        this.closeCommandPalette();
      });
    });
    if (this.inputContainerEl) {
      this.inputContainerEl.addClass("clawdian-input-container");
      this.inputContainerEl.appendChild(palette);
    }
    const removePalette = (e) => {
      if (!palette.contains(e.target)) {
        this.closeCommandPalette();
      }
    };
    setTimeout(() => {
      const handleEscape = (e) => {
        if (e.key === "Escape") {
          palette.remove();
          document.removeEventListener("click", removePalette);
          document.removeEventListener("keydown", handleEscape);
          this.commandPaletteEl = null;
        }
      };
      const handleEnter = (e) => {
        if (e.key === "Enter") {
          e.preventDefault();
          e.stopPropagation();
          const text = this.inputEl.value;
          const match = text.match(/^\/(\w+)(?:\s+(.*))?$/);
          if (match) {
            const commandId = match[1];
            const args = match[2] || "";
            this.executeCommand(commandId, args);
          }
        }
      };
      document.addEventListener("click", removePalette);
      document.addEventListener("keydown", handleEscape);
      document.addEventListener("keydown", handleEnter);
    }, 0);
  }
  closeCommandPalette() {
    if (this.commandPaletteEl) {
      this.commandPaletteEl.remove();
      this.commandPaletteEl = null;
    }
  }
  async executeCommand(commandId, args) {
    if (!this.validateCommand(commandId)) {
      new import_obsidian2.Notice(`"${commandId}" is not a valid command. Use /search, /create, /summarize, or /clear`);
      this.closeCommandPalette();
      return;
    }
    if (args === void 0) {
      const text = this.inputEl.value;
      const match = text.match(/^\/(\w+)(?:\s+(.+))?$/);
      args = (match == null ? void 0 : match[2]) || "";
    }
    switch (commandId) {
      case "search":
        await this.commandSearch(args);
        break;
      case "create":
        await this.commandCreate(args);
        break;
      case "summarize":
        await this.commandSummarize();
        break;
      case "clear":
        await this.commandClear();
        break;
    }
    this.closeCommandPalette();
  }
  async commandSearch(query) {
    var _a, _b;
    if (!query.trim()) {
      new import_obsidian2.Notice("Usage: /search <query>");
      return;
    }
    const sanitizedQuery = this.sanitizeInput(query);
    if (!sanitizedQuery) {
      new import_obsidian2.Notice("Invalid query");
      return;
    }
    new import_obsidian2.Notice(`\u{1F50D} Searching for "${sanitizedQuery}"...`);
    const files = this.app.vault.getMarkdownFiles();
    const results = [];
    for (const file of files) {
      try {
        const content = await this.app.vault.read(file);
        if (content.toLowerCase().includes(query.toLowerCase())) {
          results.push({ file, content });
          if (results.length >= 5) break;
        }
      } catch (e) {
      }
    }
    if (results.length === 0) {
      this.addMessage("assistant", `No results found for "${query}"`);
      return;
    }
    const contextParts = results.map((r) => {
      const excerpt = r.content.substring(0, 500);
      return `--- ${r.file.path} ---
${excerpt}`;
    }).join("\n\n");
    this.addMessage("user", `/search ${sanitizedQuery}`);
    this.showLoading();
    await this.plugin.addMessageToHistory({
      agentId: ((_a = this.agentSelectEl) == null ? void 0 : _a.value) || "main",
      agentName: "You",
      role: "user",
      content: `/search ${sanitizedQuery}`
    });
    await this.client.sendMessage({
      agent: ((_b = this.agentSelectEl) == null ? void 0 : _b.value) || this.plugin.settings.defaultAgent,
      content: `Found ${results.length} results for "${sanitizedQuery}". Here's what I found:

${contextParts}

Summarize these results.`,
      context: { currentFile: `Search: ${sanitizedQuery}`, fileContent: contextParts },
      sessionId: this.sessionId
    });
  }
  async commandCreate(title) {
    var _a;
    if (!title.trim()) {
      new import_obsidian2.Notice("Usage: /create <title>");
      return;
    }
    const sanitizedTitle = this.sanitizeInput(title).replace(/[^a-zA-Z0-9\s-]/g, "").trim().replace(/\s+/g, "-");
    if (!sanitizedTitle) {
      new import_obsidian2.Notice("Invalid title");
      return;
    }
    const path = `${sanitizedTitle}.md`;
    try {
      const file = await this.app.vault.create(path, `# ${title}

`);
      new import_obsidian2.Notice(`Created: ${path}`);
      const leaf = this.app.workspace.getLeaf("tab");
      await leaf.openFile(file);
      await this.plugin.addMessageToHistory({
        agentId: ((_a = this.agentSelectEl) == null ? void 0 : _a.value) || "main",
        agentName: "Assistant",
        role: "assistant",
        content: `Created note: [[${path}]]`
      });
      this.addMessage("user", `/create ${title}`);
      this.addMessage("assistant", `Created note: [[${path}]]`);
    } catch (e) {
      new import_obsidian2.Notice(`Failed to create note: ${e}`);
    }
  }
  async commandSummarize() {
    var _a, _b;
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian2.Notice("No file active. Open a note first.");
      return;
    }
    try {
      const content = await this.app.vault.read(activeFile);
      const excerpt = content.substring(0, 3e3);
      await this.plugin.addMessageToHistory({
        agentId: ((_a = this.agentSelectEl) == null ? void 0 : _a.value) || "main",
        agentName: "You",
        role: "user",
        content: `/summarize ${activeFile.name}`
      });
      this.addMessage("user", `/summarize ${activeFile.name}`);
      this.showLoading();
      await this.client.sendMessage({
        agent: ((_b = this.agentSelectEl) == null ? void 0 : _b.value) || this.plugin.settings.defaultAgent,
        content: `Please summarize this note:

---
${excerpt}
---

Provide a concise summary.`,
        context: { currentFile: activeFile.path, fileContent: excerpt },
        sessionId: this.sessionId
      });
    } catch (e) {
      new import_obsidian2.Notice(`Failed to read file: ${e}`);
    }
  }
  async commandClear() {
    this.plugin.chatHistory.messages = [];
    await this.plugin.saveChatHistory();
    this.messagesEl.empty();
    new import_obsidian2.Notice("Chat history cleared");
  }
};
var FileSuggestModal = class extends import_obsidian2.FuzzySuggestModal {
  constructor(app, chatView) {
    super(app);
    this.chatView = chatView;
    this.setPlaceholder("Search files to add...");
  }
  getItems() {
    return this.app.vault.getMarkdownFiles();
  }
  getItemText(file) {
    return file.basename;
  }
  onChooseItem(file, evt) {
    this.chatView.addFile(file);
  }
};

// src/utils/OpenClawClient.ts
var import_obsidian3 = require("obsidian");
var OpenClawClient = class {
  constructor(url, token) {
    this.ws = null;
    this.connected = false;
    this.connectionResolve = null;
    this.connectionReject = null;
    this.onMessage = null;
    this.onError = null;
    this.onConnect = null;
    this.onDisconnect = null;
    this.onAuthError = null;
    this.onAgentsUpdated = null;
    this.agents = [];
    this.url = url;
    this.token = token;
  }
  getAgents() {
    return this.agents;
  }
  async fetchAgents() {
    if (!this.ws || this.ws.readyState !== WebSocket.OPEN) {
      return [];
    }
    return new Promise((resolve) => {
      const requestId = this.generateId();
      const timeout = setTimeout(() => resolve([]), 5e3);
      const originalHandler = this.handleMessage.bind(this);
      this.handleMessage = (data) => {
        var _a, _b;
        if (data.id === requestId) {
          clearTimeout(timeout);
          this.handleMessage = originalHandler;
          if (data.type === "res" && ((_a = data.payload) == null ? void 0 : _a.agents)) {
            this.agents = data.payload.agents;
            (_b = this.onAgentsUpdated) == null ? void 0 : _b.call(this, this.agents);
          }
          resolve(this.agents);
        } else {
          originalHandler(data);
        }
      };
      this.ws.send(JSON.stringify({
        type: "req",
        id: requestId,
        method: "agents.list",
        params: {}
      }));
    });
  }
  validateGatewayUrl(url) {
    try {
      const parsed = new URL(url);
      return parsed.protocol === "wss:" || parsed.protocol === "ws:";
    } catch (e) {
      return false;
    }
  }
  updateConfig(url, token) {
    if (!this.validateGatewayUrl(url)) {
      throw new Error("Invalid Gateway URL. Must use wss:// or ws:// protocol.");
    }
    this.url = url;
    this.token = token;
    if (this.ws) this.disconnect();
  }
  isConnected() {
    return this.connected;
  }
  async connect() {
    return new Promise((resolve, reject) => {
      this.connectionResolve = resolve;
      this.connectionReject = reject;
      if (!this.validateGatewayUrl(this.url)) {
        const errorMsg = "Invalid Gateway URL. Must use wss:// or ws:// protocol.";
        console.error("[Clawdian] " + errorMsg);
        reject(new Error(errorMsg));
        return;
      }
      try {
        this.ws = new WebSocket(this.url);
        this.ws.onopen = () => {
        };
        this.ws.onmessage = (event) => {
          var _a;
          try {
            const data = JSON.parse(event.data);
            this.handleMessage(data);
          } catch (e) {
            (_a = this.onMessage) == null ? void 0 : _a.call(this, event.data);
          }
        };
        this.ws.onerror = (err) => {
          var _a, _b;
          console.error("[Clawdian] WebSocket error:", err);
          (_a = this.onError) == null ? void 0 : _a.call(this, new Error("WebSocket connection failed"));
          (_b = this.connectionReject) == null ? void 0 : _b.call(this, new Error("WebSocket connection failed"));
          this.connectionResolve = null;
          this.connectionReject = null;
        };
        this.ws.onclose = () => {
          var _a;
          this.connected = false;
          (_a = this.onDisconnect) == null ? void 0 : _a.call(this);
        };
      } catch (err) {
        reject(err instanceof Error ? err : new Error(String(err)));
      }
    });
  }
  handleConnectChallenge(_nonce) {
    this.sendConnectRequest();
  }
  handleMessage(data) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l, _m;
    if (data.type === "event" && data.event === "connect.challenge") {
      const nonce = (_a = data.payload) == null ? void 0 : _a.nonce;
      if (nonce) this.handleConnectChallenge(nonce);
      return;
    }
    switch (data.type) {
      case "event":
        if (data.event === "agent" || data.event === "chat") {
          (_b = this.onMessage) == null ? void 0 : _b.call(this, JSON.stringify(data));
        }
        break;
      case "res":
        if (((_c = data.payload) == null ? void 0 : _c.type) === "hello-ok" || data.ok === true) {
          this.connected = true;
          (_d = this.onConnect) == null ? void 0 : _d.call(this);
          (_e = this.connectionResolve) == null ? void 0 : _e.call(this);
          this.connectionResolve = null;
          this.connectionReject = null;
        } else if (data.error) {
          const errorMsg = data.error.message || String(data.error) || "Connection failed";
          console.error("[Clawdian] Connection error:", errorMsg);
          (_f = this.onAuthError) == null ? void 0 : _f.call(this, errorMsg);
          (_g = this.connectionReject) == null ? void 0 : _g.call(this, new Error(errorMsg));
          this.connectionResolve = null;
          this.connectionReject = null;
        } else if ((_h = data.payload) == null ? void 0 : _h.agents) {
          this.agents = data.payload.agents;
          (_i = this.onAgentsUpdated) == null ? void 0 : _i.call(this, this.agents);
        }
        break;
      case "auth":
      case "connected":
        if (data.ok === true) {
          this.connected = true;
          (_j = this.onConnect) == null ? void 0 : _j.call(this);
          (_k = this.connectionResolve) == null ? void 0 : _k.call(this);
          this.connectionResolve = null;
          this.connectionReject = null;
        } else if (data.error) {
          const errorMsg = data.error.message || String(data.error) || "Auth failed";
          console.error("[Clawdian] Auth error:", errorMsg);
          (_l = this.onAuthError) == null ? void 0 : _l.call(this, errorMsg);
          (_m = this.connectionReject) == null ? void 0 : _m.call(this, new Error(errorMsg));
          this.connectionResolve = null;
          this.connectionReject = null;
        }
        break;
      default:
    }
  }
  sendConnectRequest() {
    if (!this.ws || this.ws.readyState !== WebSocket.OPEN) {
      console.error("[Clawdian] WebSocket not ready");
      return;
    }
    const request = {
      type: "req",
      id: this.generateId(),
      method: "connect",
      params: {
        minProtocol: 3,
        maxProtocol: 3,
        client: {
          id: "cli",
          version: "1.0.1",
          platform: this.getPlatform(),
          mode: "ui"
        },
        role: "operator",
        scopes: ["operator.read", "operator.write", "operator.admin"],
        auth: {
          token: this.token
        }
      }
    };
    this.ws.send(JSON.stringify(request));
  }
  generateId() {
    return Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);
  }
  getPlatform() {
    if (import_obsidian3.Platform.isMacOS) return "macos";
    if (import_obsidian3.Platform.isWin) return "windows";
    if (import_obsidian3.Platform.isLinux) return "linux";
    if (import_obsidian3.Platform.isMobile) return "mobile";
    return "unknown";
  }
  sendMessage(msg) {
    return new Promise((resolve, reject) => {
      var _a;
      if (!this.ws || this.ws.readyState !== WebSocket.OPEN) {
        reject(new Error("Not connected"));
        return;
      }
      const agentId = msg.agent || "main";
      const sessionKey = `agent:${agentId}:session:${msg.sessionId || this.generateId()}`;
      let fullPrompt = msg.content;
      if ((_a = msg.context) == null ? void 0 : _a.currentFile) {
        let contextHeader = `Context: Currently viewing "${msg.context.currentFile}"`;
        if (msg.context.fileContent) {
          const excerpt = msg.context.fileContent.slice(0, 3e3).trim();
          contextHeader += `

File excerpt:
${excerpt}`;
        }
        fullPrompt = `${contextHeader}

---

${msg.content}`;
      }
      const request = {
        type: "req",
        id: "msg-" + this.generateId(),
        method: "chat.send",
        params: {
          sessionKey,
          message: fullPrompt,
          idempotencyKey: this.generateId()
        }
      };
      this.ws.send(JSON.stringify(request));
      resolve(request.id);
    });
  }
  disconnect() {
    if (this.ws) {
      this.ws.close();
      this.ws = null;
    }
    this.connected = false;
  }
  async getSessionStatus(sessionKey) {
    if (!this.ws || this.ws.readyState !== WebSocket.OPEN) return null;
    return new Promise((resolve) => {
      const requestId = this.generateId();
      const timeout = setTimeout(() => {
        resolve(null);
      }, 5e3);
      const originalHandler = this.handleMessage.bind(this);
      this.handleMessage = (data) => {
        var _a;
        if (data.id === requestId) {
          clearTimeout(timeout);
          this.handleMessage = originalHandler;
          const payload = data.payload;
          const state = (payload == null ? void 0 : payload.state) || (payload == null ? void 0 : payload.status) || ((_a = payload == null ? void 0 : payload.session) == null ? void 0 : _a.state) || (data.ok ? "running" : null);
          resolve(state);
        } else {
          originalHandler(data);
        }
      };
      this.ws.send(JSON.stringify({
        type: "req",
        id: requestId,
        method: "sessions.get",
        params: { sessionKey }
      }));
    });
  }
};

// src/components/TokenModal.ts
var import_obsidian4 = require("obsidian");
var TokenModal = class extends import_obsidian4.Modal {
  constructor(app, gatewayUrl, onConnect) {
    super(app);
    this.token = "";
    this.gatewayInput = null;
    this.tokenInput = null;
    this.gatewayUrl = gatewayUrl;
    this.onConnect = onConnect;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("clawdian-token-modal");
    contentEl.createEl("h2", { text: "Connect to OpenClaw" });
    const instructions = contentEl.createEl("div", { cls: "clawdian-instructions" });
    instructions.createEl("p", { text: "To get your gateway token:" });
    const ol = instructions.createEl("ol");
    const step1 = ol.createEl("li");
    step1.createEl("span", { text: "Open a terminal and run: " });
    step1.createEl("code", { text: "openclaw dashboard" });
    ol.createEl("li", { text: 'Click on "Overview" in the dashboard' });
    ol.createEl("li", { text: "Copy the gateway token" });
    new import_obsidian4.Setting(contentEl).setName("Gateway URL").setDesc("Your OpenClaw Gateway WebSocket URL").addText((text) => {
      this.gatewayInput = text.inputEl;
      text.setPlaceholder("wss://your-gateway-url");
      text.setValue(this.gatewayUrl);
    });
    new import_obsidian4.Setting(contentEl).setName("Gateway token").setDesc("Paste the token from your dashboard").addText((text) => {
      this.tokenInput = text.inputEl;
      text.setPlaceholder("your-gateway-token");
      text.inputEl.type = "password";
      this.tokenInput.addEventListener("input", () => {
        this.token = this.tokenInput.value;
      });
    });
    const securityNote = contentEl.createEl("div", { cls: "clawdian-security-note" });
    securityNote.createEl("small", {
      text: "\u{1F512} Your token is stored securely using Obsidian's Secret Storage API."
    });
    new import_obsidian4.Setting(contentEl).addButton((btn) => {
      btn.setButtonText("Connect").setCta().onClick(() => {
        const gateway = this.gatewayInput.value.trim();
        const token = this.tokenInput.value.trim();
        if (!gateway) {
          new import_obsidian4.Notice("Please enter the gateway URL");
          return;
        }
        if (!token) {
          new import_obsidian4.Notice("Please enter the gateway token");
          return;
        }
        this.close();
        this.onConnect(gateway, token);
      });
    }).addButton((btn) => {
      btn.setButtonText("Cancel").onClick(() => this.close());
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/main.ts
var ClawdianPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.tokenKey = "clawdian-gateway-token";
    this.chatHistory = { messages: [], lastUpdated: 0 };
    this.HISTORY_FILE = ".clawdian/chat-history.json";
    // Debug logging - set DEBUG_CLAWDIAN=1 in .env for production debugging
    this.debug = false;
  }
  debugLog(...args) {
    if (this.debug) {
    }
  }
  debugError(...args) {
    console.error("[Clawdian]", ...args);
  }
  async onload() {
    this.debugLog("Plugin loading...");
    await this.loadSettings();
    await this.loadChatHistory();
    const token = await this.loadToken();
    this.client = new OpenClawClient(
      this.settings.gatewayUrl,
      token || ""
    );
    this.setupClientCallbacks();
    this.registerView(
      VIEW_TYPE_CHAT,
      (leaf) => new ChatView(leaf, this.client, this)
    );
    this.addRibbonIcon("message-square", "Open Clawdian", () => {
      void this.activateView();
    });
    this.addCommand({
      id: "open-clawdian",
      name: "Open clawdian chat",
      callback: () => {
        void this.activateView();
      }
    });
    this.addSettingTab(new ClawdianSettingTab(this.app, this));
    if (this.settings.autoConnect && token) {
      this.debugLog("Auto-connect enabled, attempting connection...");
      void this.tryConnect().then((connected) => {
        if (connected) {
          this.debugLog("Auto-connect successful");
        }
      }).catch((err) => {
        this.debugLog("Auto-connect failed:", err.message);
      });
    }
    this.debugLog("Plugin loaded");
  }
  /**
   * Load chat history from file
   */
  async loadChatHistory() {
    try {
      const adapter = this.app.vault.adapter;
      const exists = await adapter.exists(this.HISTORY_FILE);
      if (exists) {
        const content = await adapter.read(this.HISTORY_FILE);
        const parsed = JSON.parse(content);
        this.chatHistory = parsed;
      } else {
        this.chatHistory = { messages: [], lastUpdated: Date.now() };
      }
    } catch (e) {
      const errorMsg = e instanceof Error ? e.message : String(e);
      this.debugError("Error loading history:", errorMsg);
      this.chatHistory = { messages: [], lastUpdated: Date.now() };
    }
  }
  /**
   * Save chat history to file
   */
  async saveChatHistory() {
    try {
      const adapter = this.app.vault.adapter;
      const dir = ".clawdian";
      try {
        const dirExists = await adapter.exists(dir);
        if (!dirExists) {
          await adapter.mkdir(dir);
        }
      } catch (folderError) {
        const folderErrorMsg = folderError instanceof Error ? folderError.message : String(folderError);
        if (!folderErrorMsg.includes("already exists")) {
          throw folderError;
        }
      }
      this.chatHistory.lastUpdated = Date.now();
      const content = JSON.stringify(this.chatHistory, null, 2);
      await adapter.write(this.HISTORY_FILE, content);
    } catch (e) {
      const errorMsg = e instanceof Error ? e.message : String(e);
      this.debugError("Failed to save history:", errorMsg);
    }
  }
  /**
   * Add message to history
   */
  async addMessageToHistory(message) {
    const newMessage = {
      ...message,
      id: this.generateId(),
      timestamp: Date.now()
    };
    this.chatHistory.messages.push(newMessage);
    if (this.chatHistory.messages.length > 500) {
      this.chatHistory.messages = this.chatHistory.messages.slice(-500);
    }
    await this.saveChatHistory();
  }
  generateId() {
    return Date.now().toString(36) + Math.random().toString(36).substring(2, 10);
  }
  /**
   * Load token from Obsidian's Secret Storage
   */
  async loadToken() {
    try {
      const adapter = this.app.vault.adapter;
      if (adapter == null ? void 0 : adapter.read) {
        const secretPath = `.obsidian/plugins/${this.manifest.id}/.secrets/token`;
        try {
          const data = await adapter.read(secretPath);
          if (data && data.trim()) {
            return data.trim();
          }
        } catch (e) {
          return null;
        }
      }
      return null;
    } catch (e) {
      return null;
    }
  }
  /**
   * Save token to Obsidian's Secret Storage
   */
  async saveToken(token) {
    const adapter = this.app.vault.adapter;
    if ((adapter == null ? void 0 : adapter.write) && (adapter == null ? void 0 : adapter.mkdir)) {
      const secretDir = `.obsidian/plugins/${this.manifest.id}/.secrets`;
      const secretPath = `${secretDir}/token`;
      try {
        await adapter.mkdir(secretDir);
      } catch (e) {
      }
      await adapter.write(secretPath, token);
    } else {
      console.error("[Clawdian] Secret Storage not available!");
      throw new Error("Secret Storage not available");
    }
  }
  /**
   * Clear stored token from Secret Storage
   */
  async clearToken() {
    const adapter = this.app.vault.adapter;
    if (adapter == null ? void 0 : adapter.remove) {
      const secretPath = `.obsidian/plugins/${this.manifest.id}/.secrets/token`;
      try {
        await adapter.remove(secretPath);
      } catch (e) {
      }
    }
  }
  setupClientCallbacks() {
    this.client.onConnect = () => {
    };
    this.client.onDisconnect = () => {
    };
    this.client.onError = (err) => {
      console.error("[Clawdian] Client error:", err);
    };
    this.client.onAuthError = (msg) => {
      console.error("[Clawdian] Auth error:", msg);
      this.showTokenModal();
    };
  }
  showTokenModal() {
    const modal = new TokenModal(
      this.app,
      this.settings.gatewayUrl,
      async (gateway, token) => {
        this.settings.gatewayUrl = gateway;
        await this.saveSettings();
        await this.saveToken(token);
        this.client.updateConfig(gateway, token);
        try {
          await this.client.connect();
        } catch (err) {
          const errorMsg = err instanceof Error ? err.message : String(err);
          new import_obsidian5.Notice("\u274C Connection failed: " + errorMsg);
        }
      }
    );
    modal.open();
  }
  async tryConnect() {
    const token = await this.loadToken();
    if (!token) {
      return false;
    }
    try {
      await this.client.connect();
      return true;
    } catch (err) {
      const errorMsg = err instanceof Error ? err.message : String(err);
      console.error("[Clawdian] Connection failed:", errorMsg);
      return false;
    }
  }
  onunload() {
    var _a;
    (_a = this.client) == null ? void 0 : _a.disconnect();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_CHAT);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (!leaf) return;
      await leaf.setViewState({ type: VIEW_TYPE_CHAT, active: true });
    }
    workspace.revealLeaf(leaf);
    if (!this.client.isConnected()) {
      await this.tryConnect();
    }
  }
};
